### ISSUE TITLE
Error when using the mffmatlabio plugin in fieldtrip

### ISSUE THREAD

**Issue by lemonistas** [arnodelorme/mffmatlabio#24]
Hi, 
I am getting an error message when trying to import an .mff file using the importer plugin in fieldtrip, I'm using the latest version from github. The error message reads: "undefined function or variable 'eeglab_options'. "

The only workaround I've found so far is starting EEGLAB so it creates 'eeglab_options', then the import in fieldtrip works.
![Screen Shot 2020-04-28 at 10 31 09](https://user-images.githubusercontent.com/28633862/80466412-cedf3880-893c-11ea-8f79-48e590c2789c.png)

Please let me know what you think.

Best,
Clemens

**Comment by arnodelorme** [comment]
I have fixed the issue in version 3.3

**Comment by lemonistas** [comment]
Unfortunately I'm still getting the very same error message with version 3.3 
<img width="1976" alt="Bildschirmfoto 2020-04-28 um 22 30 03" src="https://user-images.githubusercontent.com/28633862/80534795-1f3bb200-89a0-11ea-8628-bec67211e1b7.png">

**Comment by arnodelorme** [comment]
I have modified the function mff_import.m 
Would you mind to download this function and try again?

https://github.com/arnodelorme/mffmatlabio/blob/master/mff_import.m

Best wishes,

Arno

**Comment by lemonistas** [comment]
Thank you very much, Arno!

It works with the function you posted. :-)

Kind regards,
Clemens

**Comment by arnodelorme** [comment]
Thank you Clemens
