### ISSUE TITLE
Wrong trial number returned by mff_import

### ISSUE THREAD

**Issue by ftadel** [arnodelorme/mffmatlabio#4]
One of our users reported an issue related with reading a .mff file:
https://neuroimage.usc.edu/forums/t/importing-pre-processed-and-epoched-data-egi-mff/10178

The example .mff file can be downloaded here:
https://www.dropbox.com/sh/cdwljgkbcbdxs0g/AABF1ihB5QPegf1mvf0jcFqRa?dl=0

The function mff_import() returns a structure with:
EEG.trials=1
EEG.pnts=201
size(EEG.data) = [257×90450 single]

Shouldn't trials be set to 90450/201 = 450 instead?

**Comment by ftadel** [comment]
There is more incoherent information read from the same file:
```
                pnts: 201
               srate: 1000
                xmin: -0.2000
                xmax: 1
```
Should we use the xmin/xmax (-200ms-1000ms) or the pnts/srate values (-200ms-0ms)?
Why is the .times field not filled?

**Comment by arnodelorme** [comment]
Yes, this is correct. This is fixed in EEGLAB by calling the checking function. I think it is safe for a quick fix to have (after you get back the structure) EEG.trials=size(EEG.data,2)/EEG.pnts

I will implement a fix a release a new version (there is also a bug for writing events which I have fixed and another one which I have not fixed yet).

Thanks Francois,

Arno

**Comment by ftadel** [comment]
Thanks

And how are we supposed to interpret the wrong timing? (pnts/srate/xmin/xmax)

The .epoch field is also missing.

**Comment by ftadel** [comment]
Btw, eeg_checkset does not fix the missing .epoch field.
And it doesn't fix the incoherence between the time fields (pnts/srate/xmin/xmax).
The output .times (from -200ms to 0s) does not seem to be what the user is expecting.

**Comment by ftadel** [comment]
I take this last comment back, eeg_checkset does fix the epoch field, but it is difficult to have this working outside of EEGLAB. Proposed changes to have eeg_checkset working in Brainstorm:
https://github.com/arnodelorme/mffmatlabio/pull/5

The question of this particular dataset remains open, reading it generates tons of warnings and does not seem to include the full epochs (only the times between -200ms and 0s seem to be read). I will ask our user to post the dataset here as well.
Could you have a look at it, just to check if the problem is coming from the dataset or from the reading functions?

Thanks

**Comment by ftadel** [comment]
Example dataset:
https://www.dropbox.com/sh/lbc25tfvw5dtftt/AADJPsnU5G0XwrWgisknCyQla?dl=0

**Comment by ftadel** [comment]
Have you got a chance to look at this dataset?

**Comment by arnodelorme** [comment]
Would you mind to share again the dataset. The link is broken.

**Comment by ftadel** [comment]
I think it's this dataset:
https://www.dropbox.com/s/djofgwxebyd4nu0/0027_Sungjin_20170403_114721_Hfil_Lfil_seg_bcr_blc_ref.mff.zip?dl=0

**Comment by arnodelorme** [comment]
Thank you Francois,

Arno

**Comment by arnodelorme** [comment]
Hi Francois,

The problem had been fixed already. Is it OK to include your file in the test suite?
I will keep you posted for a new release, probably within a month.
Best wishes,

Arno

**Comment by ftadel** [comment]
I don't know, this is not my dataset. 
I asked the user who posted in on the Brainstorm forum:
https://neuroimage.usc.edu/forums/t/importing-pre-processed-and-epoched-data-egi-mff/10178/6
